name: snatch
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  clipboard_watcher: ^0.3.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2 
  dio: ^5.4.0
  open_filex: ^4.4.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
